// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutocompleteController from "./autocomplete_controller"
application.register("autocomplete", AutocompleteController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import SelectController from "./select_controller"
application.register("select", SelectController)
