require:
  - rubocop-minitest

plugins:
  - rubocop-capybara
  - rubocop-rails
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - lib/generators/**/*.rb
    - .annotaterb.yml
    - db/migrate/**

  TargetRubyVersion: 3.3
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes