require:
  - rubocop-capybara
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - lib/generators/**/*.rb
    - .annotaterb.yml
    - db/migrate/**

  TargetRubyVersion: 3.0
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
