services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    image: looseends-dev
    build:
      context: .
      target: development
    # Note: Does not run yarn watchers like bin/dev
    command: /bin/bash -c "rm -f /tmp/server.pid && bundle exec rails server -b 0.0.0.0 -P /tmp/server.pid"
    ports:
      - 3000:3000
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://postgres@db/looseends_development
    volumes:
      - .:/webapp
    depends_on:
      - db
    tty: true
    stdin_open: true
